// Shared interface copy. Project and experience narratives live in portfolio.ts.
export const copy = {
  hero: {
    greeting: "Hi, I’m",
    title: ["I’m a computer science student", "at UNC Chapel Hill who likes", "building useful software and", "experimenting with new technology."],
    edition: "PORTFOLIO / 2026",
    work: "View my work",
    about: "More about me",
    scroll: "SCROLL THROUGH MY WORK",
    path: "PROJECTS / EXPERIENCE / ABOUT",
  },
  process: {
    label: "HOW THE PIECES CONNECT",
    steps: ["Write.", "Connect.", "Ship."],
  },
  work: {
    label: "MY PROJECTS",
    title: ["Selected", "projects."],
    intro: ["What each project does,", "and how it works."],
    caseLink: "What I built",
    live: "Live Demo",
    demo: "Live Demo",
    open: "Read about",
  },
  experience: {
    label: "EXPERIENCE",
    title: ["Where I’ve", "worked."],
    intro: ["I build AI systems, make useful software,", "and help people learn to code."],
    latest: "CURRENT",
  },
  skills: { label: "TOOLS I USE", title: ["What I", "work with"] },
  about: {
    label: "ABOUT ME",
    title: ["A bit", "about me."],
    art: "UNC CHAPEL HILL · COMPUTER SCIENCE",
    index: "ARMAN / 001",
    resume: "My resume",
  },
  contact: {
    label: "GET IN TOUCH",
    eyebrow: "CONTACT",
    title: ["Get", "in", "touch."],
    note: "I’d be glad to hear from you.",
  },
  nav: {
    home: "Portfolio home",
    work: "Projects",
    experience: "Experience",
    about: "About",
    skills: "Skills",
    contact: "Contact",
    talk: "Say hello",
    open: "Open navigation",
    description: "Find your way around my work.",
    title: "navigation",
    skip: "Skip to content",
  },
  links: {
    missing: "Not linked yet",
    external: "(opens in a new tab)",
    github: "GitHub",
    linkedin: "LinkedIn",
    resume: "Resume",
    back: "Back to my projects",
    home: "Back to home",
    top: "Back to top",
    source: "View Code",
    viewCode: "View Code",
    live: "Live Demo",
  },
  footer: "Next.js · TypeScript · Vercel",
  case: {
    pending: "I’m still adding the details for this project.",
    role: "MY WORK",
    year: "YEAR",
    duration: "TIME",
    next: "NEXT PROJECT",
    chapters: ["What it’s for", "How I built it", "What it does"],
  },
  preview: {
    note: "An illustration of how it works, not live output.",
    alt: "Arman Hassan’s software projects and computer science portfolio.",
    title: "01 / PORTFOLIO",
    lines: ["Software projects by Arman Hassan.", "Projects by Arman Hassan."],
  },
  notFound: {
    label: "404 / PAGE NOT FOUND",
    title: ["This page", "isn’t here."],
    description: "The link might be wrong. You can head back to my projects.",
  },
  error: {
    label: "SOMETHING WENT WRONG",
    title: ["Let’s try", "that again."],
    description: "This page couldn’t load. Try opening it again.",
    retry: "Try again",
  },
  scene: {
    caption: "SCROLL-CONTROLLED REQUEST DIAGRAM",
    scroll: "SCROLL TO EXPLORE",
    terminal: "system / example trace",
    alt: "A processor connected to client and service nodes. Scroll to separate its layers and follow a request through the system.",
  },
  motion: {
    pause: "Pause motion",
    resume: "Resume motion",
    pauseAll: "Pause all animation",
    resumeAll: "Resume all animation",
  },
} as const;

export const sceneStages = [
  {
    label: "01 / SOURCE",
    command: "$ npm run build",
    output: "source → modules → application",
  },
  {
    label: "02 / CONNECT",
    command: "$ curl -i /api/hello",
    output: "client → gateway → service",
  },
  {
    label: "03 / RESPOND",
    command: "HTTP/1.1 200 OK",
    output: '{ "message": "Hello, world." }',
  },
];
