// Shared interface copy. Project and experience narratives live in portfolio.ts.
export const copy = {
  hero: {
    greeting: "Hi, I’m",
    title: ["I have a few ideas.", "Fortunately, I know how to code."],
    subtitle: "Full stack development \u00b7 LLM integration \u00b7 Backend APIs \u00b7 Databases \u00b7 Cloud deployment",
    education: "Computer science + Data science \u00b7 UNC \u201927",
    edition: "PORTFOLIO / 2026",
    work: "See my projects",
    about: "About me",
    scroll: "SCROLL THROUGH MY PROJECTS",
    path: "CODE → SYSTEMS → PROJECTS",
  },
  process: {
    label: "HOW THE PIECES CONNECT",
    steps: ["Write.", "Connect.", "Ship."],
  },
  work: {
    label: "MY PROJECTS",
    title: ["Selected", "projects."],
    intro: ["What each project does,", "and how it works."],
    caseLink: "What I built",
    live: "Live",
    demo: "Live Demo",
    open: "Read about",
  },
  experience: {
    label: "EXPERIENCE",
    title: ["Where I’ve", "worked."],
    latest: "CURRENT",
  },
  skills: { label: "TOOLS I USE", title: ["What I", "work with."] },
  about: {
    label: "ABOUT ME",
    title: ["A bit", "about me."],
    art: "CODE, QUESTIONS, AND A LOT OF LEARNING.",
    index: "ARMAN / 001",
    resume: "My resume",
  },
  contact: {
    label: "GET IN TOUCH",
    eyebrow: "HAVE A QUESTION OR AN IDEA?",
    title: ["Want to", "build", "something?"],
    note: "I’d be glad to hear from you.",
  },
  nav: {
    home: "Portfolio home",
    work: "Projects",
    experience: "Experience",
    about: "About",
    skills: "Skills",
    contact: "Contact",
    talk: "Say hello",
    open: "Open navigation",
    description: "Find your way around my projects.",
    title: "navigation",
    skip: "Skip to content",
  },
  links: {
    missing: "Not linked yet",
    external: "(opens in a new tab)",
    github: "GitHub",
    linkedin: "LinkedIn",
    resume: "Resume",
    back: "Back to my projects",
    home: "Back to home",
    top: "Back to top",
    source: "View Code",
    viewCode: "View Code",
    live: "Live project",
  },
  footer: "WRITTEN, BUILT, AND STILL LEARNING",
  case: {
    pending: "I’m still adding the details for this project.",
    role: "MY WORK",
    year: "YEAR",
    duration: "TIME",
    next: "NEXT PROJECT",
    chapters: ["What it’s for", "How I built it", "What it does"],
  },
  preview: {
    note: "An illustration of how it works, not live output.",
    alt: "Arman Hassan’s software projects and computer science portfolio.",
    title: "01 / PORTFOLIO",
    lines: ["From code to systems.", "AI agents and interactive tools."],
  },
  notFound: {
    label: "404 / PAGE NOT FOUND",
    title: ["This page", "isn’t here."],
    description: "The link might be wrong. You can head back to my projects.",
  },
  error: {
    label: "SOMETHING WENT WRONG",
    title: ["Let’s try", "that again."],
    description: "This page couldn’t load. Try opening it again.",
    retry: "Try again",
  },
  scene: {
    caption: "A LOOK INSIDE THE SYSTEM",
    scroll: "SCROLL TO EXPLORE",
    terminal: "system / example trace",
    alt: "A processor connected to client and service nodes. Scroll to separate its layers and follow a request through the system.",
  },
  motion: {
    pause: "Pause motion",
    resume: "Resume motion",
    pauseAll: "Pause all animation",
    resumeAll: "Resume all animation",
  },
  status: {
    branch: "main",
    root: "~/arman",
    label: "Reading position",
    palette: "Open command palette",
    shortcut: "Ctrl K",
    openToWork: "open to work",
  },
  palette: {
    title: "Command palette",
    description: "Jump to a section or project, or open a link. Use the arrow keys and Enter.",
    placeholder: "Type a command or search…",
    empty: "No matching commands.",
    groups: { navigate: "Go to section", projects: "Projects", actions: "Actions" },
    copyEmail: "Copy email address",
    copied: "Email copied to clipboard",
    resume: "Open resume",
    github: "Open GitHub",
    linkedin: "Open LinkedIn",
    top: "Back to top",
  },
} as const;

export const sceneStages = [
  {
    label: "01 / SOURCE",
    command: "$ npm run build",
    output: "source → modules → application",
  },
  {
    label: "02 / CONNECT",
    command: "$ curl -i /api/hello",
    output: "client → gateway → service",
  },
  {
    label: "03 / RESPOND",
    command: "HTTP/1.1 200 OK",
    output: '{ "message": "Hello, world." }',
  },
];
